 
post http://localhost:5162/v1/products
Content-Type: application/json

{
  "title": "Sample Product 2",
  "description": "A test product 2",
  "slug": "sample-product 2",
  "price": 50.00
}
###

GET http://localhost:5162/v1/products
Accept: application/json

###

GET http://localhost:5162/v1/products/0aee8c26-80eb-426d-bf5b-d0536638b198
Accept: application/json

###

PUT http://localhost:5162/v1/products/0aee8c26-80eb-426d-bf5b-d0536638b198
Content-Type: application/json

{
  "title": "Updated Product",
  "description": "Updated description",
  "slug": "updated-product",
  "price": 29.99
}

###

DELETE http://localhost:5162/v1/products/0aee8c26-80eb-426d-bf5b-d0536638b198

###
